on: push
name: Workflow
jobs:
  app-tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: "#p3tG0Ap1"
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer install --no-scripts
 
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Execute tests (Unit and Feature tests) using PHPUnit
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: php artisan test
 
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/